# Generated by Django 3.1.2 on 2020-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
